export const PricingList = {
  PRICING_EN: [
    {
      title: "Basic Package",
      description: "Perfect for small and emerging restaurants",
      price: "Free",
      duration: "100%",
      features: [
        "Up to 100 invoices per month",
        "Basic cashback system",
        "Monthly reports",
        "Email support",
        "Single branch management",
      ],
      recommend: false,
      color: "from-blue-500 to-blue-600",
    },
    {
      title: "Professional Package",
      description: "Best suited for medium-sized restaurants",
      price: "999 EGP",
      duration: "month",
      features: [
        "Unlimited invoices",
        "Advanced cashback and coupons",
        "Detailed reports and analytics",
        "24/7 phone support",
        "Manage up to 5 branches",
        "Customer reviews",
        "Instant notifications",
      ],
      recommend: true,
      color: "from-purple-500 to-purple-600",
    },
    {
      title: "Enterprise Package",
      description: "For large chains and corporations",
      price: "Custom",
      duration: null,
      features: [
        "Custom solutions",
        "POS system integration",
        "Dedicated account manager",
        "Team training",
        "Unlimited branches",
        "Custom API",
        "Advanced AI-powered analytics",
      ],
      recommend: false,
      color: "from-amber-500 to-amber-600",
    },
  ],
  PRICING_AR: [
    {
      title: "الباقة الأساسية",
      description: "مثالي للمطاعم الصغيرة والناشئة",
      price: "مجاني",
      duration: "١٠٠٪",
      features: [
        "حتى 100 فاتورة شهرياً",
        "نظام كاش باك أساسي",
        "تقارير شهرية",
        "دعم عبر الإيميل",
        "إدارة فرع واحد",
      ],
      recommend: false,
      color: "from-blue-500 to-blue-600",
    },
    {
      title: "الباقة المهنية",
      description: "الأنسب للمطاعم المتوسطة",
      price: "٩٩٩ ج.م",
      duration: "شهر",
      features: [
        "فواتير غير محدودة",
        "كاش باك وكوبونات متقدمة",
        "تقارير وتحليلات مفصلة",
        "دعم هاتفي 24/7",
        "إدارة حتى 5 فروع",
        "تقييمات العملاء",
        "إشعارات فورية",
      ],
      recommend: true,
      color: "from-purple-500 to-purple-600",
    },
    {
      title: "باقة المؤسسات",
      description: "للسلاسل الكبيرة والمؤسسات",
      price: "حسب الطلب",
      duration: "شهري/سنوي",
      features: [
        "حلول مخصصة",
        "تكامل مع أنظمة POS",
        "مدير حساب مخصص",
        "تدريب للفريق",
        "فروع غير محدودة",
        "API مخصص",
        "تحليلات متقدمة بالذكاء الاصطناعي",
      ],
      recommend: false,
      color: "from-amber-500 to-amber-600",
    },
  ],
};
